server:
  port: 8080
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service-auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: auth-service-user
          uri: lb://auth-service
          predicates:
            - Path=/user/**

        - id: auth-service-oauth2
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**,/.well-known/**,/login

        - id: chat-service-workspace-chats
          uri: lb://chat-service
          predicates:
            - Path=/workspaces/*/chats/**

        - id: chat-service-user-chats
          uri: lb://chat-service
          predicates:
            - Path=/chats/**

        - id: chat-service-files
          uri: lb://chat-service
          predicates:
            - Path=/files/**

        - id: workspace-service
          uri: lb://workspace-service
          predicates:
            - Path=/workspaces/**

        - id: workspace-service-boards
          uri: lb://workspace-service
          predicates:
            - Path=/boards/**

        - id: workspace-service-notifications
          uri: lb://workspace-service
          predicates:
            - Path=/notifications/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**

        - id: chat-service-ws
          uri: lb:ws://chat-service
          predicates:
            - Path=/ws/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server-backend.itconnect.svc.cluster.local:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
