server:
  port: 8080
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service-backend:8081/oauth2/jwks

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service-auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: JwtCookie

        - id: auth-service-user
          uri: lb://auth-service
          predicates:
            - Path=/user/**
          filters:
            - name: JwtCookie

        - id: auth-service-oauth2
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**,/.well-known/**,/login,/register,/login/oauth2/**
          filters:
            - name: JwtCookie

        # CORE
        - id: core-service-api
          uri: lb://core-service
          predicates:
            - Path=/api/**
        - id: core-service-ws
          uri: lb:ws://core-service
          predicates:
            - Path=/ws/**

        # INTEGRATION
        - id: integration-service
          uri: lb://integration-service
          predicates:
            - Path=/integrations/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server-backend:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}