server:
  port: 8081
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/itconnect_auth
    username: postgres
    password: "12345"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 3333ergewgewfe
            client-secret: 3333322gggggefeefwe
            scope:
              - openid
              - profile
              - email
          github:
            client-id: jknhbtrf45676uy
            client-secret: 3456yhuhbgvferftgyhu
            scope:
              - read:user
              - user:email

  cloud:
    compatibility-verifier:
      enabled: false

security:
  jwt:
    secret-key: 13615f1179d5e7fa8376af3f3c0b127e27a65c2782ef2ff9da1eb6a7f294d18a
    expiration-time: 3600000

app:
  frontend:
    redirect-url: http://localhost:5173/dashboard
  internal:
    api-key: change-me-in-config

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server-backend:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}