server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres-service.itconnect.svc.cluster.local:5432/itconnect
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

supabase:
  s3:
    endpoint: http://localhost:9000/storage/v1/s3
    region: eu-central-1
    access-key: dummy-access-key
    secret-key: dummy-secret-key
    bucket: dummy-bucket

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server-backend.itconnect.svc.cluster.local:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
